CONSUMER_KEY: 'yBg5lc6pCC50D2QGneDSwA'
CONSUMER_SECRET: 'ZSpbhvjkOzdGIKqZCgL8ZSl72cwpUVV8xGZbYSCbM'
OAUTH_TOKEN: '2215681765-6BUYUVZWFojJcPNBKkzakre8GJWuEJlNoRByvul'
OAUTH_SECRET: 'kAPVBV0qAeXV6SnZMdJwjoOikb2K3wbnWnND1AF0rE0d9'

***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
