CONSUMER_KEY: yBg5lc6pCC50D2QGneDSwA
CONSUMER_SECRET: ZSpbhvjkOzdGIKqZCgL8ZSl72cwpUVV8xGZbYSCbM
OAUTH_TOKEN: 2215681765-6BUYUVZWFojJcPNBKkzakre8GJWuEJlNoRByvul
OAUTH_SECRET: kAPVBV0qAeXV6SnZMdJwjoOikb2K3wbnWnND1AF0rE0d9

# Twitter authentication for handle @markovQaurelius
# account password is Init.Index2<=list?
# email account is MarkovQAurelius@yahoo.com
# email password is the same
