name: Generate tweet

on:
  schedule:
    - cron: '2 10 * * *'

  # Manually trigger this action
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.2'
        bundler-cache: true

    - name: Add tweet to file
    - run: |
        bundle exec rake generate_tweet >> "tweets/$(date -u +%Y-%b-%d).md"

    - name: Commit file to repo
      run: echo "going to commit, yes"
