name: Generate tweet

on:
  schedule:
    - cron: '2 10 * * *'

  # Manually trigger this action
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.2'
        bundler-cache: true

    - name: Add tweet to file
      run: |
        touch "${{ github.workspace }}/tweets/$(date -u +%Y-%b-%d).md"
        bundle exec rake generate_tweet >> "${{ github.workspace }}/tweets/$(date -u +%Y-%b-%d).md"
        cat "${{ github.workspace }}/tweets/$(date -u +%Y-%b-%d).md"

    - name: Create commits
      run: |
        git config user.name 'Chris Boette'
        git config user.email 'chrisbodhi@users.noreply.github.com'
        git add -A
        git commit -m "Add tweet for $(date -u +%Y-%b-%d)."

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
