name: Rubocopy

on:
  push
  
  # Manually trigger this action
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Rubocop checks
      uses: luizfonseca/github-actions-rubocop@1.5.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
