name: Send tweet

on:
#  schedule:
#    - cron: '2 14 * * *'

  # Manually trigger this action
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Into the ether
      env:
        API_KEY: ${{secrets.API_KEY}}
        API_SECRET_KEY: ${{secrets.API_SECRET_KEY}}
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}} 
        ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
        FILE_PATH: "./tweets/"
      run: go run main.go
